const questions = {
  FoodMenu: [
    {
  question: "Which ingredients are in the Truffle Soup from the first course?",
  choice: [
    "Chicken Consommé, Root Vegetables, Black Truffles, Foie Gras, Mushrooms, Puff Pastry",
    "Beef Broth, Potatoes, Carrots, Truffle Oil, Croutons",
    "Vegetable Stock, Lentils, Onions, Truffle Salt, Baguette",
    "Miso Broth, Tofu, Seaweed, Enoki Mushrooms, Rice Crackers",
  ],
  answer: "Chicken Consommé, Root Vegetables, Black Truffles, Foie Gras, Mushrooms, Puff Pastry",
  explanation: "The Truffle Soup contains chicken consommé, root vegetables, black truffles, foie gras, mushrooms, and puff pastry.",
},
{
  question: "What is NOT an ingredient in the Baby Beet Salad from the first course?",
  choice: [
    "Avocado",
    "Yogurt",
    "Sunflower Seeds",
    "Truffle Vinaigrette",
  ],
  answer: "Truffle Vinaigrette",
  explanation: "Truffle vinaigrette is not listed in the Baby Beet Salad; it's in the Mushroom Tart.",
},
{
  question: "Which cheese is used in the Mushroom Tart?",
  choice: [
    "Triple Cream Brie",
    "Gruyère",
    "Comté",
    "Ricotta",
  ],
  answer: "Triple Cream Brie",
  explanation: "Triple Cream Brie is included in the Mushroom Tart.",
},
{
  question: "What is true about the Charcuterie 'Du Moment'?",
  choice: [
    "It contains mushrooms and cheese",
    "The preparation changes daily",
    "It is always served with foie gras",
    "It is vegan",
  ],
  answer: "The preparation changes daily",
  explanation: "The charcuterie's preparation changes daily.",
},
{
  question: "Which green is included in the Kale Salad?",
  choice: [
    "Radicchio",
    "Spinach",
    "Arugula",
    "Endive",
  ],
  answer: "Radicchio",
  explanation: "Radicchio is one of the greens listed in the Kale Salad.",
},
{
  question: "Which component is NOT in the Steak Tartare?",
  choice: [
    "Gruyère Waffle",
    "Quail Egg",
    "Gruyère Crisps",
    "Brandy Peppercorn Sauce",
  ],
  answer: "Brandy Peppercorn Sauce",
  explanation: "Brandy Peppercorn Sauce is paired with beef, not the tartare.",
},
{
  question: "Which fish is used in the Salmon & Caviar first course?",
  choice: [
    "King Salmon",
    "Atlantic Salmon",
    "Sockeye Salmon",
    "Steelhead Trout",
  ],
  answer: "King Salmon",
  explanation: "King Salmon is the fish in the Salmon & Caviar dish.",
},
{
  question: "What fruit compote accompanies the Matcha Cured Torchon of Foie Gras?",
  choice: [
    "Strawberry & Rhubarb",
    "Blueberry & Lemon",
    "Raspberry & Pear",
    "Fig & Apple",
  ],
  answer: "Strawberry & Rhubarb",
  explanation: "The dish includes a strawberry & rhubarb compote.",
},
{
  question: "Which broth is used in the Warm Jumbo Asparagus?",
  choice: [
    "Dashi Broth",
    "Chicken Broth",
    "Vegetable Broth",
    "Beef Broth",
  ],
  answer: "Dashi Broth",
  explanation: "Dashi broth is used with the warm jumbo asparagus.",
},
{
  question: "Which dish in the first course always has a changing preparation?",
  choice: [
    "Charcuterie 'Du Moment'",
    "Baby Beet Salad",
    "Truffle Soup",
    "Kale Salad",
  ],
  answer: "Charcuterie 'Du Moment'",
  explanation: "Charcuterie 'Du Moment' has a preparation that changes daily.",
},
{
  question: "Which sauce is served with the Seared Sea Scallops?",
  choice: [
    "Saffron Vanilla Sauce",
    "Lobster Sabayon",
    "Garlic Scape Butter",
    "Brandy Peppercorn Sauce",
  ],
  answer: "Saffron Vanilla Sauce",
  explanation: "Seared Sea Scallops come with saffron vanilla sauce.",
},
{
  question: "What meat is featured in the Cote de Porc?",
  choice: [
    "Berkshire Pork Rack",
    "Beef Strip Loin",
    "Lamb",
    "Duck",
  ],
  answer: "Berkshire Pork Rack",
  explanation: "Cote de Porc uses lightly smoked Berkshire pork rack.",
},
{
  question: "Which sauce accompanies the Grilled Strip Loin Of Beef?",
  choice: [
    "Sauce Béarnaise",
    "Lobster Sabayon",
    "Saffron Vanilla Sauce",
    "Dashi Broth",
  ],
  answer: "Sauce Béarnaise",
  explanation: "Grilled Strip Loin of Beef is served with sauce béarnaise.",
},
{
  question: "Which dish is vegan and gluten free?",
  choice: [
    "Artichoke À la Barigoule",
    "Braised Lamb Ravioli",
    "Mushroom Tart",
    "Charcuterie 'Du Moment'",
  ],
  answer: "Artichoke À la Barigoule",
  explanation: "Artichoke À la Barigoule is marked as gluten free & vegan.",
},
{
  question: "What is a key vegetable in the Lobster Cavatelli?",
  choice: [
    "Fava Beans",
    "Spinach",
    "Radish",
    "Corn",
  ],
  answer: "Fava Beans",
  explanation: "Lobster Cavatelli contains fava beans.",
},
{
  question: "What unique element is included with the Hudson Valley Rohan Duck?",
  choice: [
    "Duck Skin Dukkah Crumble",
    "Lobster Sabayon",
    "Potato Rosti",
    "Gruyère Waffle",
  ],
  answer: "Duck Skin Dukkah Crumble",
  explanation: "Duck skin dukkah crumble is on the Hudson Valley Rohan Duck.",
},
{
  question: "What is a feature of the Black Olive Poached Halibut?",
  choice: [
    "Basil Pesto",
    "Foie Gras",
    "Saffron Vanilla Sauce",
    "Gruyère Crisps",
  ],
  answer: "Basil Pesto",
  explanation: "Basil pesto is served with the halibut.",
},
{
  question: "Which dessert includes vanilla-lavender ice cream?",
  choice: [
    "Blueberry Lemon Tart",
    "Vacherin",
    "Crème Brûlée",
    "Chocolate Caramel Mousse",
  ],
  answer: "Blueberry Lemon Tart",
  explanation: "Blueberry lemon tart is served with vanilla-lavender ice cream.",
},
{
  question: "Which dessert has a strawberry ice cream and basil meringue?",
  choice: [
    "Vacherin",
    "Crème Brûlée",
    "Blueberry Lemon Tart",
    "Chocolate Caramel Mousse",
  ],
  answer: "Vacherin",
  explanation: "Vacherin features strawberry ice cream and basil meringue.",
},
{
  question: "Which dessert is served with a buckwheat tuile?",
  choice: [
    "Crème Brûlée",
    "Vacherin",
    "Chocolate Caramel Mousse",
    "TableSide Ice Cream",
  ],
  answer: "Crème Brûlée",
  explanation: "Crème Brûlée is accompanied by a buckwheat tuile.",
},
{
  question: "Which ingredient gives the Truffle Soup its signature flavor?",
  choice: [
    "Black Truffles",
    "Gruyère Cheese",
    "Lobster",
    "Asparagus",
  ],
  answer: "Black Truffles",
  explanation: "Black truffles are the key ingredient in the Truffle Soup.",
},
{
  question: "Which component is not found in the Baby Beet Salad?",
  choice: [
    "Avocado",
    "Yogurt",
    "Sprouted Quinoa",
    "Puff Pastry",
  ],
  answer: "Puff Pastry",
  explanation: "Puff pastry is not in the Baby Beet Salad; it's in the Truffle Soup.",
},
{
  question: "Which nut is found in the Mushroom Tart?",
  choice: [
    "Almond (Almond Sable)",
    "Pistachio",
    "Walnut",
    "Hazelnut",
  ],
  answer: "Almond (Almond Sable)",
  explanation: "Almond sable is a component of the Mushroom Tart.",
},
{
  question: "What makes the Matcha Cured Torchon of Foie Gras unique?",
  choice: [
    "It is cured with matcha and served with strawberry & rhubarb compote",
    "It is pan-seared with apricot glaze",
    "It is served with truffle honey",
    "It is baked in puff pastry",
  ],
  answer: "It is cured with matcha and served with strawberry & rhubarb compote",
  explanation: "This foie gras is cured with matcha and served with fruit compote.",
},
{
  question: "Which vegetable is shaved and included with Warm Jumbo Asparagus?",
  choice: [
    "Rhubarb",
    "Carrot",
    "Fennel",
    "Radish",
  ],
  answer: "Rhubarb",
  explanation: "Shaved rhubarb is served with the warm jumbo asparagus.",
},
{
  question: "Which item on the menu is marked with an asterisk (*)?",
  choice: [
    "Beausoleil Oysters",
    "Grilled Strip Loin of Beef",
    "Charcuterie 'Du Moment'",
    "Baby Beet Salad",
  ],
  answer: "Beausoleil Oysters",
  explanation: "Beausoleil Oysters are marked with an asterisk and a +$5 supplement.",
},
{
  question: "Which protein is the main component in the Steak Tartare?",
  choice: [
    "Beef",
    "Duck",
    "Lamb",
    "Salmon",
  ],
  answer: "Beef",
  explanation: "Steak tartare is traditionally made from raw beef.",
},
{
  question: "What type of bread accompanies the Salmon & Caviar dish?",
  choice: [
    "Grilled Baguette",
    "Sourdough",
    "Rye Bread",
    "Focaccia",
  ],
  answer: "Grilled Baguette",
  explanation: "Salmon & Caviar is served with grilled baguette.",
},
{
  question: "Which dish is served with creamy Comté dressing?",
  choice: [
    "Kale Salad",
    "Charcuterie 'Du Moment'",
    "Warm Jumbo Asparagus",
    "Grilled Strip Loin of Beef",
  ],
  answer: "Kale Salad",
  explanation: "The Kale Salad is dressed with creamy Comté dressing.",
},
{
  question: "What ingredient is NOT found in the Grilled Strip Loin of Beef?",
  choice: [
    "Potato Rosti",
    "Asparagus",
    "Sauce Béarnaise",
    "Fava Beans",
  ],
  answer: "Fava Beans",
  explanation: "Fava beans are in the Lobster Cavatelli, not the beef dish.",
},
{
  question: "What sauce is featured with the Black Olive Poached Halibut?",
  choice: [
    "Sauce Vierge",
    "Saffron Vanilla Sauce",
    "Lobster Sabayon",
    "Sherry Dressing",
  ],
  answer: "Sauce Vierge",
  explanation: "Black Olive Poached Halibut comes with sauce vierge.",
},
{
  question: "Which first course features both King Salmon and caviar?",
  choice: [
    "Salmon & Caviar",
    "Truffle Soup",
    "Steak Tartare",
    "Warm Jumbo Asparagus",
  ],
  answer: "Salmon & Caviar",
  explanation: "King Salmon Crudo and caviar are the focus of this dish.",
},
{
  question: "What vegetable is in the Seared Sea Scallops dish?",
  choice: [
    "Braised Fennel",
    "Radish",
    "Carrot",
    "Spinach",
  ],
  answer: "Braised Fennel",
  explanation: "Braised fennel is included with the scallops.",
},
{
  question: "What ingredient gives the Cote de Porc a tangy accent?",
  choice: [
    "Pickled Mustard Seeds",
    "Cherry Port Jus",
    "Spring Peas",
    "Basil Pesto",
  ],
  answer: "Pickled Mustard Seeds",
  explanation: "Pickled mustard seeds provide tanginess to the pork dish.",
},
{
  question: "What type of sauce is paired with Hudson Valley Rohan Duck?",
  choice: [
    "Confit 'Bastilla'",
    "Duck Skin Dukkah Crumble",
    "Rhubarb Sauce",
    "Mint Pesto",
  ],
  answer: "Duck Skin Dukkah Crumble",
  explanation: "The duck is finished with duck skin dukkah crumble.",
},
{
  question: "Which main course is gluten free and vegan?",
  choice: [
    "Artichoke À la Barigoule",
    "Braised Lamb Ravioli",
    "Cote de Porc",
    "Lobster Cavatelli",
  ],
  answer: "Artichoke À la Barigoule",
  explanation: "Artichoke À la Barigoule is gluten free and vegan.",
},
{
  question: "What dessert features honey chantilly and strawberry ice cream?",
  choice: [
    "Vacherin",
    "Blueberry Lemon Tart",
    "Chocolate Caramel Mousse",
    "TableSide Ice Cream",
  ],
  answer: "Vacherin",
  explanation: "Vacherin includes honey chantilly and strawberry ice cream.",
},
{
  question: "Which dessert contains a salted caramel flourless biscuit?",
  choice: [
    "Chocolate Caramel Mousse",
    "Crème Brûlée",
    "Vacherin",
    "Blueberry Lemon Tart",
  ],
  answer: "Chocolate Caramel Mousse",
  explanation: "The mousse dessert features a salted caramel flourless biscuit.",
},
{
  question: "What topping is served with the Crème Brûlée?",
  choice: [
    "Buckwheat Tuile",
    "Almond Tuile",
    "Basil Meringue",
    "Poached Sugar Snap Peas",
  ],
  answer: "Buckwheat Tuile",
  explanation: "Crème Brûlée comes with a buckwheat tuile.",
},
{
  question: "Which ice cream flavor is paired with the Chocolate Caramel Mousse?",
  choice: [
    "Coffee",
    "Vanilla-Lavender",
    "Strawberry",
    "Raspberry Sorbet",
  ],
  answer: "Coffee",
  explanation: "Chocolate Caramel Mousse is paired with coffee ice cream.",
},
{
  question: "What is unique about the TableSide Ice Cream dessert?",
  choice: [
    "The preparation changes daily and it is limited in availability",
    "It always includes strawberry flavor",
    "It is made with Gruyère",
    "It contains truffle oil",
  ],
  answer: "The preparation changes daily and it is limited in availability",
  explanation: "TableSide Ice Cream is a special dessert with changing preparation and limited availability.",
},
{
  question: "Which dish is made with a torchon preparation?",
  choice: [
    "Matcha Cured Torchon of Foie Gras",
    "Grilled Strip Loin of Beef",
    "Steak Tartare",
    "Artichoke À la Barigoule",
  ],
  answer: "Matcha Cured Torchon of Foie Gras",
  explanation: "The 'torchon' technique is used for the foie gras.",
},
{
  question: "What is the main vegetable in the Artichoke À la Barigoule?",
  choice: [
    "Artichoke",
    "Broccoli",
    "Potato",
    "Sunchoke",
  ],
  answer: "Artichoke",
  explanation: "Artichoke is the featured vegetable.",
},
{
  question: "Which dish features potato rosti?",
  choice: [
    "Grilled Strip Loin of Beef",
    "Seared Sea Scallops",
    "Lobster Cavatelli",
    "Kale Salad",
  ],
  answer: "Grilled Strip Loin of Beef",
  explanation: "Potato rosti is served with the beef.",
},
{
  question: "Which green is included in the Grilled Strip Loin Of Beef dish?",
  choice: [
    "Asparagus",
    "Radicchio",
    "Spring Peas",
    "Baby Vegetables",
  ],
  answer: "Asparagus",
  explanation: "Asparagus is listed in the beef dish components.",
},
{
  question: "Which dish features brandy peppercorn sauce?",
  choice: [
    "Grilled Strip Loin Of Beef",
    "Steak Tartare",
    "Cote de Porc",
    "Braised Lamb Ravioli",
  ],
  answer: "Grilled Strip Loin Of Beef",
  explanation: "Beef is served with both béarnaise and brandy peppercorn sauce.",
},
{
  question: "What kind of seafood is featured in the Lobster Cavatelli?",
  choice: [
    "Maine Lobster",
    "Sea Scallops",
    "King Salmon",
    "Halibut",
  ],
  answer: "Maine Lobster",
  explanation: "Maine lobster is a primary component of Lobster Cavatelli.",
},
{
  question: "Which spring vegetable is included with the Lobster Cavatelli?",
  choice: [
    "Spring Onions",
    "Fennel",
    "Radish",
    "Kale",
  ],
  answer: "Spring Onions",
  explanation: "Spring onions are part of the dish.",
},
{
  question: "What grain is found in the Cote de Porc?",
  choice: [
    "Local Grains",
    "Barley",
    "Quinoa",
    "Farro",
  ],
  answer: "Local Grains",
  explanation: "Cote de Porc is served with local grains.",
},
{
  question: "Which dish includes cherry port jus?",
  choice: [
    "Cote de Porc",
    "Braised Lamb Ravioli",
    "Grilled Strip Loin of Beef",
    "Black Olive Poached Halibut",
  ],
  answer: "Cote de Porc",
  explanation: "Cherry port jus is paired with pork.",
},
{
  question: "Which dish is described as 'baby vegetables à la Grecque'?",
  choice: [
    "Artichoke À la Barigoule",
    "Kale Salad",
    "Braised Lamb Ravioli",
    "Steak Tartare",
  ],
  answer: "Artichoke À la Barigoule",
  explanation: "Baby vegetables à la Grecque are in the artichoke dish.",
},
{
  question: "What type of broth is used in the Warm Jumbo Asparagus?",
  choice: [
    "Dashi Broth",
    "Vegetable Broth",
    "Beef Broth",
    "Chicken Consommé",
  ],
  answer: "Dashi Broth",
  explanation: "Dashi broth flavors the asparagus.",
},
{
  question: "What is a ramp?",
  choice: [
    "A wild spring onion",
    "A French cheese",
    "A type of mushroom",
    "A pickled radish",
  ],
  answer: "A wild spring onion",
  explanation: "Ramps are wild spring onions, often foraged.",
},
{
  question: "Which dish has 'cream Comté dressing'?",
  choice: [
    "Kale Salad",
    "Mushroom Tart",
    "Warm Jumbo Asparagus",
    "Blueberry Lemon Tart",
  ],
  answer: "Kale Salad",
  explanation: "The Kale Salad uses creamy Comté dressing.",
},
{
  question: "What type of caviar is served with King Salmon Crudo?",
  choice: [
    "Domestic Caviar",
    "Osetra Caviar",
    "Trout Roe",
    "None",
  ],
  answer: "Domestic Caviar",
  explanation: "Domestic caviar accompanies the salmon crudo.",
},
{
  question: "Which dish lists both sunchoke purée and artichokes?",
  choice: [
    "Seared Sea Scallops",
    "Artichoke À la Barigoule",
    "Black Olive Poached Halibut",
    "Braised Lamb Ravioli",
  ],
  answer: "Seared Sea Scallops",
  explanation: "Seared Sea Scallops are served with both.",
},
{
  question: "Which cheese appears in the Steak Tartare?",
  choice: [
    "Gruyère",
    "Comté",
    "Brie",
    "Ricotta",
  ],
  answer: "Gruyère",
  explanation: "Gruyère is used in both the waffle and crisps.",
},
{
  question: "Which dessert has a flourless component?",
  choice: [
    "Chocolate Caramel Mousse",
    "Crème Brûlée",
    "Vacherin",
    "TableSide Ice Cream",
  ],
  answer: "Chocolate Caramel Mousse",
  explanation: "It features a salted caramel flourless biscuit.",
},
{
  question: "What ingredient is NOT in the Mushroom Tart?",
  choice: [
    "Caramelized Onions",
    "Almond Sable",
    "Triple Cream Brie",
    "Gruyère Crisps",
  ],
  answer: "Gruyère Crisps",
  explanation: "Gruyère crisps are in Steak Tartare, not the Mushroom Tart.",
},
{
  question: "Which menu item comes with a sherry dressing?",
  choice: [
    "Baby Beet Salad",
    "Kale Salad",
    "Charcuterie 'Du Moment'",
    "Steak Tartare",
  ],
  answer: "Baby Beet Salad",
  explanation: "The salad is finished with sherry dressing.",
},
{
  question: "Which dish includes pickled mustard seeds?",
  choice: [
    "Cote de Porc",
    "Braised Lamb Ravioli",
    "Seared Sea Scallops",
    "Mushroom Tart",
  ],
  answer: "Cote de Porc",
  explanation: "Pickled mustard seeds are paired with the pork.",
},
{
  question: "What is a 'Bastilla' in the Hudson Valley Rohan Duck?",
  choice: [
    "A type of duck confit pastry",
    "A cheese crisp",
    "A grilled vegetable",
    "A dessert tuile",
  ],
  answer: "A type of duck confit pastry",
  explanation: "A bastilla is a savory pastry, here made with duck confit.",
},

  ],
  Wines: [
    {
      question: "What style of wine is Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Sparkling wine",
        "Red wine",
        "Rosé wine",
        "Dessert wine",
      ],
      answer: "Sparkling wine",
      explanation: "Pierre Sparr Crémant d'Alsace is a sparkling wine from Alsace, France.",
    },
    {
      question: "Which grape varieties are used in Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Pinot Noir and Chardonnay",
        "Pinot Blanc and Auxerrois",
        "Riesling and Gewürztraminer",
        "Merlot and Cabernet Sauvignon",
      ],
      answer: "Pinot Blanc and Auxerrois",
      explanation: "This Crémant is made from Pinot Blanc and Auxerrois grapes.",
    },
    {
      question: "Which country produces Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Italy",
        "France",
        "Spain",
        "Germany",
      ],
      answer: "France",
      explanation: "The wine comes from France.",
    },
    {
      question: "Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV is from which French wine region?",
      choice: [
        "Bordeaux",
        "Burgundy",
        "Alsace",
        "Champagne",
      ],
      answer: "Alsace",
      explanation: "This wine is made in the Alsace region of France.",
    },
    {
      question: "What color best describes Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Dark red",
        "Light yellow with green reflections",
        "Rose pink",
        "Amber gold",
      ],
      answer: "Light yellow with green reflections",
      explanation: "The wine is light yellow with green reflections.",
    },
    {
      question: "Which aromas are found in the nose of Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Black cherry and tobacco",
        "Galia melon, sweet woodruff, and dried mango",
        "Blueberry and oak",
        "Strawberry and cream",
      ],
      answer: "Galia melon, sweet woodruff, and dried mango",
      explanation: "The nose offers galia melon, sweet woodruff, and dried mango aromas.",
    },
    {
      question: "What type of acidity is present in Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Soft and mild",
        "Crisp, lemony acidity",
        "No acidity",
        "Sweet acidity",
      ],
      answer: "Crisp, lemony acidity",
      explanation: "This Crémant has crisp, lemony acidity.",
    },
    {
      question: "How is the finish described for Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Short and dry",
        "Long aftertaste",
        "No finish",
        "Bitter and sharp",
      ],
      answer: "Long aftertaste",
      explanation: "The finish is described as a long aftertaste.",
    },
    {
      question: "How are the bubbles (mousseux) described in Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV?",
      choice: [
        "Soft",
        "Harsh",
        "No bubbles",
        "Extremely aggressive",
      ],
      answer: "Soft",
      explanation: "The mousseux (bubbles) are soft and pleasant.",
    },
    {
      question: "What happens to Pierre Sparr Crémant d'Alsace Pinot Blanc/Auxerrois Alsace NV as it sits in the glass?",
      choice: [
        "It becomes sweeter",
        "It opens to a more complex sparkling brut",
        "It loses all aroma",
        "It becomes bitter",
      ],
      answer: "It opens to a more complex sparkling brut",
      explanation: "With time in the glass, the wine opens further to a complex sparkling brut.",
    },
    {
      question: "What is the vintage of Chateau Chesnaie-Moriniere Muscadet Pays Nantais?",
      choice: [
        "2020",
        "2021",
        "2022",
        "2019",
      ],
      answer: "2022",
      explanation: "The vintage of this wine is 2022.",
    },
    {
      question: "Which grape variety is used in Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022?",
      choice: [
        "Chardonnay",
        "Muscadet",
        "Sauvignon Blanc",
        "Pinot Gris",
      ],
      answer: "Muscadet",
      explanation: "The varietal for this wine is Muscadet.",
    },
    {
      question: "Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022 comes from which country?",
      choice: [
        "Italy",
        "France",
        "Spain",
        "Germany",
      ],
      answer: "France",
      explanation: "This wine is from France.",
    },
    {
      question: "In which sub-region is Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022 produced?",
      choice: [
        "Champagne",
        "Lower Loire",
        "Bordeaux",
        "Rhone Valley",
      ],
      answer: "Lower Loire",
      explanation: "The wine comes from the Lower Loire sub-region.",
    },
    {
      question: "What is the appellation of Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022?",
      choice: [
        "Pays Nantais",
        "Sancerre",
        "Pouilly-Fumé",
        "Chablis",
      ],
      answer: "Pays Nantais",
      explanation: "The appellation is Pays Nantais.",
    },

    {
      question: "Which aromas best describe Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022?",
      choice: [
        "Bright, vibrant aromas reminiscent of crushed oyster shells",
        "Ripe strawberries and cream",
        "Toasty oak and vanilla",
        "Rich chocolate and coffee",
      ],
      answer: "Bright, vibrant aromas reminiscent of crushed oyster shells",
      explanation: "The wine has bright, vibrant aromas reminiscent of crushed oyster shells.",
    },
    {
      question: "How would you describe the palate of Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022?",
      choice: [
        "Sweet and full-bodied",
        "Bone-dry, light-bodied with apple and pear fruit",
        "Heavy and tannic",
        "Soft and low in acidity",
      ],
      answer: "Bone-dry, light-bodied with apple and pear fruit",
      explanation: "The wine is bone-dry and light-bodied, with apple and pear fruit.",
    },
    {
      question: "What kind of acidity and notes does Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022 have?",
      choice: [
        "Low acidity and floral notes",
        "High acidity with minerally, citrus and briny notes",
        "Moderate acidity with herbal notes",
        "No acidity and spicy notes",
      ],
      answer: "High acidity with minerally, citrus and briny notes",
      explanation: "This wine features high acidity with minerally, citrus, and briny notes.",
    },
    {
      question: "How is the finish of Chateau Chesnaie-Moriniere Muscadet Pays Nantais 2022 described?",
      choice: [
        "Rich and sweet",
        "Short and flat",
        "Fresh and clean with nice complexity",
        "Heavy and lingering",
      ],
      answer: "Fresh and clean with nice complexity",
      explanation: "The finish is fresh and clean with nice complexity.",
    },
    {
      question: "What is the vintage of Hugel Classic Pinot Gris Alsace?",
      choice: [
        "2021",
        "2022",
        "2023",
        "2020",
      ],
      answer: "2023",
      explanation: "The vintage is 2023.",
    },
    {
      question: "Which grape variety is used in Hugel Classic Pinot Gris Alsace 2023?",
      choice: [
        "Riesling",
        "Pinot Gris",
        "Gewürztraminer",
        "Chardonnay",
      ],
      answer: "Pinot Gris",
      explanation: "The varietal is Pinot Gris.",
    },
    {
      question: "What is the label name for Hugel's Pinot Gris Alsace 2023?",
      choice: [
        "Reserve",
        "Classic",
        "Tradition",
        "Grand Cru",
      ],
      answer: "Classic",
      explanation: "The label is Classic.",
    },
    {
      question: "What country is Hugel Classic Pinot Gris Alsace 2023 from?",
      choice: [
        "Italy",
        "France",
        "Germany",
        "Austria",
      ],
      answer: "France",
      explanation: "This wine is from France.",
    },
    {
      question: "Which region produces Hugel Classic Pinot Gris Alsace 2023?",
      choice: [
        "Bordeaux",
        "Alsace",
        "Loire Valley",
        "Rhone",
      ],
      answer: "Alsace",
      explanation: "The region is Alsace.",
    },
    {
      question: "How is the body and dryness of Hugel Classic Pinot Gris Alsace 2023 described?",
      choice: [
        "Light and sweet",
        "Rich and full but still dry",
        "Medium-bodied and off-dry",
        "Heavy and sweet",
      ],
      answer: "Rich and full but still dry",
      explanation: "The wine is rich and full, but still dry.",
    },
    {
      question: "Which of the following is a characteristic of the bouquet for Hugel Classic Pinot Gris Alsace 2023?",
      choice: [
        "Strong oak and smoke aromas",
        "Soft and supple, with ripe fruit and nutty notes",
        "Citrus and floral only",
        "Heavy spice and leather",
      ],
      answer: "Soft and supple, with ripe fruit and nutty notes",
      explanation: "The bouquet is soft and supple, with ripe fruit and nutty notes.",
    },
    {
      question: "What fruit and flavor notes are found in Hugel Classic Pinot Gris Alsace 2023?",
      choice: [
        "Strawberry and blackberry",
        "Apricot, greengage, licorice, brioche, sesame seed, pistachio, and hazelnut",
        "Mango and pineapple",
        "Cherry and plum",
      ],
      answer: "Apricot, greengage, licorice, brioche, sesame seed, pistachio, and hazelnut",
      explanation: "The wine shows notes of apricot, greengage, licorice, brioche, sesame seed, pistachio, and hazelnut.",
    },
    {
      question: "How is the finish of Hugel Classic Pinot Gris Alsace 2023 described?",
      choice: [
        "Short and tart",
        "Nice long aromatic finish",
        "No finish",
        "Dry and bitter finish",
      ],
      answer: "Nice long aromatic finish",
      explanation: "The wine has a nice long aromatic finish.",
    },
    {
      question: "How is the mouthfeel of Hugel Classic Pinot Gris Alsace 2023 described?",
      choice: [
        "Light and watery",
        "Well constructed, suave, velvety, soft and almost juicy",
        "Bitter and rough",
        "Heavy and tannic",
      ],
      answer: "Well constructed, suave, velvety, soft and almost juicy",
      explanation: "The wine fills the mouth and is described as well constructed, suave, velvety, soft and almost juicy.",
    },
    {
      question: "What is the vintage of Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune?",
      choice: [
        "2020",
        "2021",
        "2022",
        "2023",
      ],
      answer: "2022",
      explanation: "The vintage is 2022.",
    },
    {
      question: "Which grape variety is used in Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022?",
      choice: [
        "Sauvignon Blanc",
        "Chardonnay",
        "Pinot Grigio",
        "Viognier",
      ],
      answer: "Chardonnay",
      explanation: "The varietal is Chardonnay.",
    },
    {
      question: "What is the label name for this Louis Jadot Chardonnay from Coté de Beaune 2022?",
      choice: [
        "Pouilly-Fuissé",
        "Chablis",
        "Mâcon-Villages",
        "Meursault",
      ],
      answer: "Mâcon-Villages",
      explanation: "The label is Mâcon-Villages.",
    },
    {
      question: "Which country does Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022 come from?",
      choice: [
        "Italy",
        "France",
        "Spain",
        "Austria",
      ],
      answer: "France",
      explanation: "This wine is from France.",
    },
    {
      question: "Which region produces Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022?",
      choice: [
        "Bordeaux",
        "Loire Valley",
        "Burgundy",
        "Champagne",
      ],
      answer: "Burgundy",
      explanation: "The region is Burgundy.",
    },
    {
      question: "What is the appellation for Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022?",
      choice: [
        "Chablis",
        "Sancerre",
        "Coté de Beaune",
        "Pouilly-Fumé",
      ],
      answer: "Coté de Beaune",
      explanation: "The appellation is Coté de Beaune.",
    },
    {
      question: "How is the oak treatment described for Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022?",
      choice: [
        "Aged in new oak",
        "Partially oaked",
        "Unoaked",
        "Heavily toasted oak",
      ],
      answer: "Unoaked",
      explanation: "This Chardonnay is 100% unoaked.",
    },
    {
      question: "How would you describe the overall style of Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022?",
      choice: [
        "Rich and creamy",
        "Bright and crisp",
        "Heavy and sweet",
        "Fruity and spicy",
      ],
      answer: "Bright and crisp",
      explanation: "The wine is bright and crisp.",
    },
    {
      question: "Which fruit note is specifically mentioned for Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022?",
      choice: [
        "Pineapple",
        "Apple",
        "Strawberry",
        "Plum",
      ],
      answer: "Apple",
      explanation: "The tasting notes mention apple.",
    },
    {
      question: "How is Louis Jadot Mâcon-Villages Chardonnay Coté de Beaune 2022 described in terms of Burgundy wine?",
      choice: [
        "A classic expression of Burgundy",
        "Unusual for Burgundy",
        "A rare sweet Burgundy",
        "Burgundy-style rosé",
      ],
      answer: "A classic expression of Burgundy",
      explanation: "It is described as a classic expression of Burgundy.",
    },
    {
      question: "What is the vintage of Bandol Domaine Le Galantin Cinsault, Grenache, Mourvedre Bandol?",
      choice: [
        "2021",
        "2022",
        "2023",
        "2020",
      ],
      answer: "2023",
      explanation: "The vintage is 2023.",
    },
    {
      question: "Which grape varieties are used in Bandol Domaine Le Galantin Bandol 2023?",
      choice: [
        "Syrah, Merlot, Cabernet Sauvignon",
        "Cinsault, Grenache, Mourvedre",
        "Pinot Noir, Chardonnay, Viognier",
        "Carignan, Tempranillo, Zinfandel",
      ],
      answer: "Cinsault, Grenache, Mourvedre",
      explanation: "The wine is a blend of Cinsault, Grenache, and Mourvedre.",
    },
    {
      question: "Which country does Bandol Domaine Le Galantin Bandol 2023 come from?",
      choice: [
        "Italy",
        "Spain",
        "France",
        "Portugal",
      ],
      answer: "France",
      explanation: "This wine is produced in France.",
    },
    {
      question: "In which French region is Bandol Domaine Le Galantin Bandol 2023 produced?",
      choice: [
        "Bordeaux",
        "Provence",
        "Alsace",
        "Loire Valley",
      ],
      answer: "Provence",
      explanation: "The wine is from the Provence region.",
    },
    {
      question: "What is the appellation of Bandol Domaine Le Galantin Bandol 2023?",
      choice: [
        "Côtes du Rhône",
        "Bandol",
        "Chablis",
        "Pouilly-Fuissé",
      ],
      answer: "Bandol",
      explanation: "The appellation is Bandol.",
    },
    {
      question: "How is the style of Bandol Domaine Le Galantin Bandol 2023 best described?",
      choice: [
        "Classic Provençal rosé",
        "Rich Bordeaux red",
        "Sweet dessert wine",
        "Sparkling Champagne",
      ],
      answer: "Classic Provençal rosé",
      explanation: "This wine is described as a classic Provençal rosé.",
    },
    {
      question: "Which fruit notes are found in Bandol Domaine Le Galantin Bandol 2023?",
      choice: [
        "Pineapple, mango, coconut",
        "Peach, nectarine, grapefruit",
        "Cherry, blackberry, plum",
        "Apple, pear, lemon",
      ],
      answer: "Peach, nectarine, grapefruit",
      explanation: "The wine shows notes of peach, nectarine, and grapefruit.",
    },
    {
      question: "How is the finish of Bandol Domaine Le Galantin Bandol 2023 described?",
      choice: [
        "Long and sweet",
        "Crisp finish",
        "Bitter and short",
        "No finish",
      ],
      answer: "Crisp finish",
      explanation: "The wine has a crisp finish.",
    },
    {
      question: "What is notable about the palate of Bandol Domaine Le Galantin Bandol 2023?",
      choice: [
        "Citrus and red fruit",
        "Heavy tannins",
        "Sweet caramel flavors",
        "Strong oak notes",
      ],
      answer: "Citrus and red fruit",
      explanation: "The palate features citrus and red fruit flavors.",
    },
    {
      question: "How are the structure and complexity of Bandol Domaine Le Galantin Bandol 2023 described?",
      choice: [
        "Light and simple",
        "Structured and complex",
        "Unbalanced and weak",
        "Overly sweet and simple",
      ],
      answer: "Structured and complex",
      explanation: "The wine is described as structured and complex.",
    },
    {
      question: "What is the vintage of Château Larose-Trintaudon Bordeaux Blend Haut-Médoc?",
      choice: [
        "2017",
        "2018",
        "2019",
        "2020",
      ],
      answer: "2019",
      explanation: "The vintage is 2019.",
    },
    {
      question: "Which grape varieties make up the blend in Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019?",
      choice: [
        "100% Cabernet Sauvignon",
        "100% Merlot",
        "60% Cabernet Sauvignon and 40% Merlot",
        "50% Cabernet Franc and 50% Merlot",
      ],
      answer: "60% Cabernet Sauvignon and 40% Merlot",
      explanation: "It is a blend of 60% Cabernet Sauvignon and 40% Merlot.",
    },
    {
      question: "What country produces Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019?",
      choice: [
        "Spain",
        "France",
        "Italy",
        "Portugal",
      ],
      answer: "France",
      explanation: "This wine is from France.",
    },
    {
      question: "Which region in France does Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019 come from?",
      choice: [
        "Loire Valley",
        "Burgundy",
        "Bordeaux",
        "Provence",
      ],
      answer: "Bordeaux",
      explanation: "The region is Bordeaux.",
    },
    {
      question: "What is the appellation for Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019?",
      choice: [
        "Saint-Émilion",
        "Pauillac",
        "Haut-Médoc",
        "Pomerol",
      ],
      answer: "Haut-Médoc",
      explanation: "The appellation is Haut-Médoc.",
    },
    {
      question: "How is the body of Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019 described?",
      choice: [
        "Light body",
        "Medium body",
        "Full body",
        "Heavy and tannic",
      ],
      answer: "Medium body",
      explanation: "The wine is described as medium body.",
    },
    {
      question: "What can you expect from the tannins in Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019?",
      choice: [
        "No tannins",
        "Soft and sweet tannins",
        "Round yet firm tannins",
        "Overly aggressive tannins",
      ],
      answer: "Round yet firm tannins",
      explanation: "The tannins are described as round yet firm.",
    },
    {
      question: "How is the finish of Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019 described?",
      choice: [
        "Bitter and short",
        "Delicious finish",
        "No finish",
        "Harsh and acidic",
      ],
      answer: "Delicious finish",
      explanation: "The wine has a delicious finish.",
    },
    {
      question: "Château Larose-Trintaudon Bordeaux Blend Haut-Médoc 2019 is typical of which wine style?",
      choice: [
        "Burgundy white",
        "Loire Valley rosé",
        "Typical Bordeaux",
        "Rhone GSM blend",
      ],
      answer: "Typical Bordeaux",
      explanation: "It is described as a typical Bordeaux from an excellent vintage.",
    },
    {
      question: "What kind of vintage is the 2019 Château Larose-Trintaudon Bordeaux Blend Haut-Médoc?",
      choice: [
        "Poor vintage",
        "Average vintage",
        "Excellent vintage",
        "Unusual vintage",
      ],
      answer: "Excellent vintage",
      explanation: "2019 is described as an excellent vintage.",
    },
    {
      question: "What is the vintage of Michel Tete ‘Cuvée Tradition’ Gamay Julienas?",
      choice: [
        "2021",
        "2022",
        "2023",
        "2020",
      ],
      answer: "2023",
      explanation: "The vintage is 2023.",
    },
    {
      question: "What is the label name of Michel Tete Gamay Julienas 2023?",
      choice: [
        "Cuvée Tradition",
        "Grand Reserve",
        "Classic",
        "Vieilles Vignes",
      ],
      answer: "Cuvée Tradition",
      explanation: "The label is ‘Cuvée Tradition’.",
    },
    {
      question: "Which grape variety is used in Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Pinot Noir",
        "Gamay",
        "Syrah",
        "Merlot",
      ],
      answer: "Gamay",
      explanation: "The varietal is Gamay.",
    },
    {
      question: "Which country does Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023 come from?",
      choice: [
        "Italy",
        "France",
        "Spain",
        "Germany",
      ],
      answer: "France",
      explanation: "This wine is from France.",
    },
    {
      question: "Which region produces Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Burgundy",
        "Beaujolais",
        "Bordeaux",
        "Loire Valley",
      ],
      answer: "Beaujolais",
      explanation: "The region is Beaujolais.",
    },
    {
      question: "What is the appellation for Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Morgon",
        "Julienas",
        "Fleurie",
        "Chiroubles",
      ],
      answer: "Julienas",
      explanation: "The appellation is Julienas.",
    },
    {
      question: "Which tasting note is highlighted for Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Fresh berry flavors",
        "Oaky vanilla flavors",
        "Spicy pepper notes",
        "Citrus and mineral",
      ],
      answer: "Fresh berry flavors",
      explanation: "The wine is packed with fresh berry flavors.",
    },
    {
      question: "How are the tannins described in Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Heavy and drying",
        "Light layer of tannin",
        "No tannins",
        "Very harsh tannins",
      ],
      answer: "Light layer of tannin",
      explanation: "A light layer of tannin gives the wine shape and potential.",
    },
    {
      question: "What is the overall style of Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Juicy and packed with fruit",
        "Rich and oaky",
        "Heavy and tannic",
        "Sweet and syrupy",
      ],
      answer: "Juicy and packed with fruit",
      explanation: "The wine is described as juicy and packed with fresh berry flavors.",
    },
    {
      question: "What does the light layer of tannin contribute to Michel Tete ‘Cuvée Tradition’ Gamay Julienas 2023?",
      choice: [
        "Sweetness",
        "Shape and potential",
        "Acidity",
        "Bitterness",
      ],
      answer: "Shape and potential",
      explanation: "The light layer of tannin gives the wine shape and potential.",
    }, {
      question: "What is the vintage of Vincent Paris Syrah Crozes-Hermitage?",
      choice: [
        "2021",
        "2022",
        "2023",
        "2020",
      ],
      answer: "2023",
      explanation: "The vintage is 2023.",
    },
    {
      question: "Which grape variety is used in Vincent Paris Syrah Crozes-Hermitage 2023?",
      choice: [
        "Cabernet Sauvignon",
        "Syrah",
        "Pinot Noir",
        "Grenache",
      ],
      answer: "Syrah",
      explanation: "The varietal is Syrah.",
    },
    {
      question: "Which country produces Vincent Paris Syrah Crozes-Hermitage 2023?",
      choice: [
        "Italy",
        "France",
        "Spain",
        "United States",
      ],
      answer: "France",
      explanation: "This wine is from France.",
    },
    {
      question: "What is the sub-region for Vincent Paris Syrah Crozes-Hermitage 2023?",
      choice: [
        "Southern Rhône",
        "Northern Rhône",
        "Bordeaux",
        "Burgundy",
      ],
      answer: "Northern Rhône",
      explanation: "The wine comes from the Northern Rhône sub-region.",
    },
    {
      question: "What is the appellation for Vincent Paris Syrah Crozes-Hermitage 2023?",
      choice: [
        "Hermitage",
        "Crozes-Hermitage",
        "Côte-Rôtie",
        "Cornas",
      ],
      answer: "Crozes-Hermitage",
      explanation: "The appellation is Crozes-Hermitage.",
    },
    {
      question: "Which floral and fruit aromas are found in Vincent Paris Syrah Crozes-Hermitage 2023?",
      choice: [
        "Violets and dark, macerated fruits",
        "Citrus and melon",
        "Apple and pear",
        "Cherry and vanilla",
      ],
      answer: "Violets and dark, macerated fruits",
      explanation: "The nose shows violets and dark, macerated fruits.",
    },
    {
      question: "Which spice note is present in Vincent Paris Syrah Crozes-Hermitage 2023?",
      choice: [
        "Black peppercorn",
        "Cinnamon",
        "Clove",
        "Nutmeg",
      ],
      answer: "Black peppercorn",
      explanation: "Hints of black peppercorn are present on the nose.",
    },
    {
      question: "How is the palate of Vincent Paris Syrah Crozes-Hermitage 2023 described?",
      choice: [
        "Juicy and approachable when young",
        "Dry and tannic",
        "Heavy and oaky",
        "Sweet and light-bodied",
      ],
      answer: "Juicy and approachable when young",
      explanation: "The wine's juicy palate makes it approachable young.",
    },
    {
      question: "Who helped Vincent Paris learn winemaking?",
      choice: [
        "His Uncle, Robert Michel",
        "His Aunt, Marie Paris",
        "His Father, Jean Paris",
        "His friend, Pierre Sparr",
      ],
      answer: "His Uncle, Robert Michel",
      explanation: "Vincent Paris learned winemaking in part from his uncle, Robert Michel.",
    },
    {
      question: "How is the ripeness of Vincent Paris Syrah Crozes-Hermitage 2023 described?",
      choice: [
        "Amazingly ripe",
        "Unripe and tart",
        "Underdeveloped",
        "Overly acidic",
      ],
      answer: "Amazingly ripe",
      explanation: "The wine is described as quite an amazingly ripe Syrah.",
    }

  ],
};
